language: ruby
rvm:
  - 1.8.7
  - 1.9.2
  - 1.9.3
  - jruby-18mode # JRuby in 1.8 mode
  - jruby-19mode # JRuby in 1.9 mode
  - rbx-18mode
  - rbx-19mode # currently in active development, may or may not work for your project
before_install: gem install bones nokogiri sinatra webrick; (ruby test/server/server.rb &); (ruby test/server/server.rb --use-ssl --port 4568 &); sleep 5
notifications:
  recipients:
    - liebler.dominik@googlemail.com
