require 'stringio'
require 'zlib'

# Public: the main Messie module
#
# this file has been generated by the bones gem!
#
# Examples:
#   version = Messie::VERSION
module Messie

  # :stopdoc:
  LIBPATH = ::File.expand_path('..', __FILE__) + ::File::SEPARATOR
  PATH = ::File.dirname(LIBPATH) + ::File::SEPARATOR
  VERSION = ::File.read(PATH + 'version.txt').strip
  # :startdoc:

  # Internal: Utility method used to require all files ending in .rb that lie in the
  # directory below this file that has the same name as the filename passed
  # in. Optionally, a specific _directory_ name can be passed in such that
  # the _filename_ does not have to be equivalent to the directory.
  #
  # Returns: an Array of files that have been require'd
  def self.require_all_libs
    base_path = File.dirname(__FILE__)
    
    files = %w(page request response string user_agent encoding/deflate encoding/gzip encoding/plain)
    files.each {|f| require File.join(base_path, 'messie', f) }
  end
end

Messie.require_all_libs
